[versions]
exposed = "0.51.1"
ktor = "2.3.12"

[libraries]
discord-webhooks = "club.minnced:discord-webhooks:0.5.7"
emojiJava = "com.vdurmont:emoji-java:4.0.0"
expiringmap = "net.jodah:expiringmap:0.5.9"
exposed-core = { module = "org.jetbrains.exposed:exposed-core", version.ref = "exposed" }
exposed-javaTime = { module = "org.jetbrains.exposed:exposed-java-time", version.ref = "exposed" }
exposed-jdbc = { module = "org.jetbrains.exposed:exposed-jdbc", version.ref = "exposed" }
google-cloud-dialogflow = "com.google.cloud:google-cloud-dialogflow:1.0.0"
google-cloud-storage = "com.google.cloud:google-cloud-storage:1.106.0"
hocon = "com.typesafe:config:1.4.1"
jda = "net.dv8tion:JDA:4.4.0_350"
ktor-client-cio = { module = "io.ktor:ktor-client-cio", version.ref = "ktor" }
ktor-client-contentNegotiation = { module = "io.ktor:ktor-client-content-negotiation", version.ref = "ktor" }
ktor-serialization-json = { module = "io.ktor:ktor-serialization-kotlinx-json", version.ref = "ktor" }
ktor-client-core = { module = "io.ktor:ktor-client-core", version.ref = "ktor" }
lettuce = "io.lettuce:lettuce-core:6.0.0.M1"
logback-classic = "ch.qos.logback:logback-classic:1.5.6"
postgresql = "org.postgresql:postgresql:42.7.3"
prettytime = "org.ocpsoft.prettytime:prettytime:4.0.4.Final"
